Repository AnalogStudiosRI/www.blissri.com, pull requests merged in 2024-05, with the labels that each got.

#26 chore/remove extraneous storybook deps
  package-lock.json
  package.json
Labels: chore

#27 content/FAQ page
  src/pages/faq.html
Labels: question, content

#29 content/issue 22 tickets page
  src/pages/tickets.html
Labels: enhancement, content

#30 feature/restore ticket and FAQ pages
  src/components/navigation/navigation.js
  src/components/navigation/navigation.spec.js
Labels: enhancement

#31 content/issue 24 home page content with 2024 event details
  src/components/event-details/event-details.js
  src/components/event-details/event-details.spec.js
  src/pages/index.html
Labels: content, first wave

#35 content/issue 24 restore home page lineup card
  src/components/lineup-card/lineup-card.spec.js
  src/components/lineup-poster/lineup-poster.js
  src/pages/index.html
  src/services/lineup-service.js
Labels: bug, content, first wave

#36 bug/fix mobile get tickets button background transparent
  src/pages/tickets.html
Labels: bug, first wave

#32 content/issue 9 blissri 2024 launch news post
  src/pages/news/2024/welcome-to-blissri.md
  src/pages/news/index.md
Labels: question, content

#38 bug/restore lineup poster margin
  src/components/lineup-poster/lineup-poster.js
Labels: bug

#43 Fix issue #40 - Add test and stories for media card
  src/components/media-card/media-card.spec.js
  src/components/media-card/media-card.stories.js
  src/components/media-card/mock-data.js
Labels: chore

#21 Feature/issue 10 photos page and blissfest 2023 content
  .gitignore
  .nvmrc
  CONTRIBUTING.md
  package-lock.json
  package.json
  src/components/media-card/media-card.js
  src/components/media-card/media-card.spec.js
  src/components/media-card/media-card.stories.js
  src/components/media-card/mock-data.js
  src/components/navigation/navigation.js
  src/components/navigation/navigation.spec.js
  src/components/photo-gallery/photo-gallery.js
  src/pages/photos/blissfest-2023.js
  src/pages/photos/index.html
  src/services/cloudinary-service.js
  src/stories/Tech_Stack.mdx
Labels: documentation, integration, content, feature

#46 bug/issue 45 footer overlapping eventbrite widget when zoomed in
  src/pages/tickets.html
Labels: bug
